#include<iostream>
using std::cout;
using std::cin;
using std::endl;
#include<cstdlib>  //rand srand
#include<ctime>  // time(0) returns current time from system

//writes a function to return a random integer generated by rand()
// between some start value and end value, inclusive

int Random( int low, int high); //prototype (allows you to use the function before calling it)

// write a function to return a randomly generated alphabetic character
char RandChar();

int main(){
    srand(time(0));

    for( int i = 0; i < 5; ++i)
        cout << Random(7, 11) << endl; // call
    return 0;

    for( int i = 0; i < 10 ; ++i)
        cout << RandChar();
    cout << endl;
    return 0;
}

//implementation
int Random(int start, int end){
    if(start > end)
        return 0;
    return start + rand() % (end - start +1);
}

char RandChar(){
    return 'a' + rand() % 26;

}